AndelaOSP/wire

src/common/navigation/Navigation.component.tsx, src/common/navigation/Navigation.scss, src/routes/routes.tsx
Add navigation links
Add navigation links
Clone repo,
Access dashboard
N/A
N/A
N/A
=> feat(Incidents): add navigation links

package.json, src/Components/App.test.jsx, test/dom.jsx, test/helpers.jsx, yarn.lock
Add test configuration
Add test configuration
- Clone repo: git clone https://github.com/AndelaOSP/wire.git
- Install packages: yarn install
- Run the project: yarn start
- Access the project: http://localhost:8080/
- Write tests and test: `yarn test`
N/A
[152068932](https://www.pivotaltracker.com/story/show/152068932)
N/A
=> #152068932 Add Tests Configuration

.eslintrc, .gitignore, package.json, src/reducers/incidentReducer.jsx, src/reducers/initialState.jsx, webpack.config.js, yarn.lock
Add linting
Add linting
`$ yarn lint:watch`
N/A
[#152593639](https://www.pivotaltracker.com/story/show/152593639)
=> #152593639 Add Linting

.github/PULL_REQUEST_TEMPLATE.md
This PR creates a standard PR template for the repo
Create a PR template
[Start here](https://github.com/AndelaOSP/wire/blob/ch-create-pr-template-152955541/.github/PULL_REQUEST_TEMPLATE.md)
N/A
This will help reduce the time taken for code review
[152955541](https://www.pivotaltracker.com/n/projects/2117172/stories/152955541)
N/A
=> #152955541 Create a PR template for succeeding PRs

package.json, src/config/index.jsx, src/pages/Login/LoginPage.Component.jsx, webpack.common.js, webpack.dev.js, webpack.prod.js, yarn.lock
Sets production and development scripts
Sets production and development scripts
N/A
Run `yarn start`: for development build
Run `yarn build`: for production build
N/A
[#154125741](https://www.pivotaltracker.com/story/show/154125741)
N/A
=> #154125741 Setup Development and Production Scripts

package.json, webpack.common.js, webpack.dev.js
Refactor Webpack Configurations
Refactor Webpack Configurations
- Remove unused scripts
- Fix image loading bug in development
- Fix linting
N/A
Run the following scripts
- `yarn start` for a development build
- `yarn build` for a production build
N/A
N/A
N/A
=> Refactor Webpack Configurations

src/Components/NavBar/NavBar.Component.jsx, src/pages/Dashboard/Dashboard.Component.jsx, src/pages/Search/Search.Component.jsx, src/pages/Search/Search.scss, src/routes.jsx
This PR creates the search page interface
Create incidents search page Interface
- Run the project on your local machine
- On the dashboard, click on the search input field
- You should be redirected to the search page
N/A
[#154066073](https://www.pivotaltracker.com/n/projects/2117172/stories/154066073)
=> #154066073 Create search page interface

src/pages/Login/LoginPage.scss
FIx Login Button
Fix Login Button
N/A
- Start the project 
- Access `http://localhost:8080/`
- You should see the login page.
N/A
N/A
=> #154080094 Fix Login Button

.coveralls.yml, package.json, yarn.lock
Add coveralls to check on tests coverage.
WHEN writing tests and having them pass i should be able to check on the percentage covered by the tests and lines of code that are uncovered by the tests,
[#154799335](https://www.pivotaltracker.com/n/projects/2117172)
=> #154799335 configure coveralls

__tests__/CustomNotification.test.jsx, package.json, src/Components/CustomNotification/CustomNotification.Component.jsx, src/Components/CustomNotification/CustomNotification.scss
Add Notifications
Whenever an event occurs that the user should be notified of, a snack-bar/toast including the message should be displayed to the user as shown in the mockups 
[Custom Notification Component](https://github.com/AndelaOSP/wire/blob/ft-add-notifications-154551427/src/Components/CustomNotification/CustomNotification.Component.jsx)
[#154551427](https://www.pivotaltracker.com/n/projects/2117172/stories/154551427/)
Success notification
Error notification
=> #154551427 Add Notifications 

README.md
Signed-off-by: Rachael Njeri <rachael.njeri@andela.com>
Updates the README.md
Adds more description about the project to the README.md
[#154755990](https://www.pivotaltracker.com/n/projects/2117172)
[#154755990](https://www.pivotaltracker.com/n/projects/2117172)
=> #154755990 Update README.md

__tests__/IncidentFilter.test.jsx, __tests__/NavBar.test.jsx, assets/images/wire_logo_v1.svg, package.json, setup.js, src/Common/NavBar/NavBar.Component.jsx, src/Common/NavBar/NavBar.scss, src/Components/Button/Button.scss, src/Components/CustomMenu/CustomMenu.Component.jsx, src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentFilter/IncidentFilter.scss, src/index.js, src/pages/Dashboard/Dashboard.Component.jsx
Update admin navbar and filter components
As user, **WHEN** I  access the admin page, 
**THEN** I should see the navbar and filters as designed in the new mockup.
[#152592788](https://www.pivotaltracker.com/story/show/152592788)
=> #152592788 Update Navbar and Filters

.prettierrc, package.json, src/Common/NavBar/NavBar.Component.jsx, src/Components/Button/Button.Component.jsx, src/Components/CustomMenu/CustomMenu.Component.jsx, src/Components/CustomNotification/CustomNotification.Component.jsx, src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentList.Component.jsx, src/Components/IncidentList/IncidentSection.Component.jsx, src/Components/PrivateRoute/PrivateRoute.Component.jsx, src/Components/Progress/Progress.Component.jsx, src/actions/incidentAction.jsx, src/actions/noteAction.jsx, src/config/index.jsx, src/helpers/auth.js, src/helpers/decodeToken.js, src/index.js, src/pages/Dashboard/Dashboard.Component.jsx, src/pages/Login/LoginPage.Component.jsx, src/pages/Search/Search.Component.jsx, src/reducers/incidentReducer.jsx, src/reducers/initialState.jsx, src/reducers/noteReducer.jsx, src/reducers/rootReducer.jsx, src/routes.jsx, src/store/store.js, webpack.common.js, webpack.dev.js, yarn.lock
Add HMR for modules only in development mode
Add script to format codebase
- add script to format codebase
$ yarn format
- enable HMR on `webpack-dev` to allow injection of changes on saving without page reload.
Change `html` or `css` code for any component rendered within the `routes.js` file. On save, check the browser immediately to confirm that the changes were added to the dom without the page reloading.
**ONLY** changes on components rendered by **`src/routes.js`** will result in `hot reload` since its the primary component hooked **`module.hot`** of webpack (that allows HMR) . When **`src/index.js`** file is changed a **FULL** page reload will occur.
[154954607](https://www.pivotaltracker.com/story/show/154954607)
=> # 154954607 Add Hot Module Replacement (HMR) and format codebase

__tests__/IncidentCard.test.jsx, __tests__/IncidentList.test.jsx, __tests__/IncidentSection.test.jsx, package.json, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentList.Component.jsx, src/Components/IncidentList/IncidentList.scss, src/Components/IncidentList/IncidentSection.Component.jsx, webpack.dev.js
Add logic to incident cards
- make incident sections scrollable
- pass incidents to correct status sections
- render appropriate flag color
- remove contentbase setting from  webpack dev
[dashboard](http://wire.andela.com:8080/dashboard)
$ yarn test
[155042641](https://www.pivotaltracker.com/story/show/155042641)
=> #155042641 Add logic to incident cards

__tests__/TimelineChat.test.jsx, __tests__/TimelineNotes.test.jsx, __tests__/TimelineSidebar.test.jsx, src/Common/NavBar/NavBar.Component.jsx, src/Common/NavBar/NavBar.scss, src/Components/Button/Button.scss, src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentList/IncidentList.scss, src/Components/TimelineChat/TimelineChat.Component.jsx, src/Components/TimelineChat/TimelineChat.scss, src/Components/TimelineNotes/TimelineNotes.Component.jsx, src/Components/TimelineNotes/TimelineNotes.scss, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx, src/Components/TimelineSidebar/TimelineSidebar.scss, src/index.html, src/pages/Dashboard/Dashboard.Component.jsx, src/pages/IncidentTimeline/IncidentTimeline.Component.jsx, src/pages/IncidentTimeline/IncidentTimeline.scss, src/routes.jsx
Create the incident timeline page
As user, WHEN I click on an incident subject,
THEN I should see the incident timeline page as designed in the mockups.
[Timeline Component](https://github.com/AndelaOSP/wire/tree/ft-incident-timeline-154799897/src/pages/IncidentTimeline)
[#154799897](https://www.pivotaltracker.com/story/show/154799897)
=> #154799897 Create incident timeline page

mock_endpoints/mockControllers.js, mock_endpoints/mockData.js, package-lock.json, package.json, src/Components/CustomMenu/CustomMenu.Component.jsx, src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentList.Component.jsx, src/pages/Dashboard/Dashboard.Component.jsx
Adds functionality to Flag's and countries button.
[#154080079](https://www.pivotaltracker.com/n/projects/2117172)
=> #154080079 Add logic for Incident Filters

package.json
Add coverage reports for tests
Add coverage reporting for tests,
N/A
`$ yarn test`
N/A
[155891947](https://www.pivotaltracker.com/story/show/155891947)
=> chore(test-coverage): WIP - add test coverage

__tests__/ErrorAction.test.jsx
Raises test coverage on the error action from 62.5% to 100%
We need to write unit tests for the errorAction, whose coverage is currently 63%
Check changed files in PR
Run `yarn test`
N/A
#155897351
N/A
=> #155897351 - Tests for errorAction

__tests__/IncidentCard.test.jsx, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentList.scss
Make the whole incident card a clickable link.
On the Incidents card, a link exists only on the subject. It has been changed so no the whole incident card is clickable
Look at files changes on the PR
Run the application , go to dashboard and click on an incident card
[#155892802](https://www.pivotaltracker.com/story/show/155892802)
=> #155892802 - Makes whole incident card clickable link

src/Components/TimelineChat/TimelineChat.Component.jsx, src/Components/TimelineNotes/TimelineNotes.Component.jsx, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx, src/pages/Search/Search.scss
- Fix validation on timeline page to avoid breakage in case of missing information
- Fix display of cards in the search page (see screenshots below)
- File changes in PR
[#156004334](https://www.pivotaltracker.com/story/show/156004334)
Before:
After:
=> 156004334 - Fix validation issues on incident timeline

__tests__/TimelineAction.test.jsx
Raises test coverage on the timeline action from 39% to 90%
We need to write unit tests for the timelineAction, whose coverage is currently 39%
Check changed files in PR
Run yarn test
N/A
#155969467
N/A
=> #155969467 - Tests for Timeline Action

__tests__/incidentAction.test.jsx
Increase Incident Action coverage to 93%
Adds test for CHANGE_STATUS
File Changes in PR
Run `yarn test` and observe coverage 
Increasing test coverage for WIRE Project 
[#155897392](https://www.pivotaltracker.com/story/show/155897392)
=> Increase test coverage for Incident Action

__tests__/ErrorAction.test.jsx, __tests__/IncidentCard.test.jsx, __tests__/IncidentSection.test.jsx, __tests__/SearchComponent.test.jsx, __tests__/TimelineAction.test.jsx, __tests__/TimelineSidebar.test.jsx, mock_endpoints/mockControllers.js, mock_endpoints/mockData.js, mock_endpoints/mockMiddleware.js, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentSection.Component.jsx, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx, src/actions/timelineAction.jsx, src/pages/IncidentTimeline/IncidentTimeline.Component.jsx, src/pages/Search/Search.Component.jsx, src/reducers/staffReducer.jsx
Update the front-end to reflect API changes
Data from the API has changed, the front-end needs to be updated as follows:
- Add a drop down to accommodate the CC field
- Update from `User` to `reporter`
- Update mock API to reflect API changes
- Refactor tests
[#156135566](https://www.pivotaltracker.com/story/show/156135566)
=> #156135566 - Update front-end to reflect API changes

__tests__/ErrorAction.test.jsx, __tests__/IncidentCard.test.jsx, __tests__/IncidentSection.test.jsx, __tests__/SearchComponent.test.jsx, __tests__/TimelineAction.test.jsx, __tests__/TimelineSidebar.test.jsx, mock_endpoints/mockControllers.js, mock_endpoints/mockData.js, mock_endpoints/mockMiddleware.js, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentSection.Component.jsx, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx, src/actions/timelineAction.jsx, src/pages/IncidentTimeline/IncidentTimeline.Component.jsx, src/pages/Search/Search.Component.jsx, src/reducers/staffReducer.jsx
=> Revert "#156135566 - Update front-end to reflect API changes"

__tests__/ErrorAction.test.jsx, __tests__/IncidentCard.test.jsx, __tests__/IncidentSection.test.jsx, __tests__/SearchComponent.test.jsx, __tests__/TimelineAction.test.jsx, __tests__/TimelineSidebar.test.jsx, mock_endpoints/mockControllers.js, mock_endpoints/mockData.js, mock_endpoints/mockMiddleware.js, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentSection.Component.jsx, src/Components/TimelineChat/TimelineChat.Component.jsx, src/Components/TimelineNotes/TimelineNotes.Component.jsx, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx, src/actions/staffAction.jsx, src/actions/timelineAction.jsx, src/pages/IncidentTimeline/IncidentTimeline.Component.jsx, src/pages/Search/Search.Component.jsx
Update the front-end to reflect API changes
Data from the API has changed, the front-end needs to be updated as follows:
- Add a drop down to accommodate the CC field
- Update from `User` to `reporter`
- Update mock API to reflect API changes
- Refactor tests
[#156135566](https://www.pivotaltracker.com/story/show/156135566)
=> Chore: Update front-end to reflect API changes

mock_endpoints/mockControllers.js, mock_endpoints/mockData.js, mock_endpoints/mockMiddleware.js, server.js, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx, src/actions/incidentAction.jsx, src/actions/timelineAction.jsx, src/config/index.jsx, src/pages/Search/Search.Component.jsx
Update the front-end
- Fix listing of selected CCd associates
- Update mock API data format to match current staging API data format
- Add search endpoint to mock API
- Update Search to use new search endpoint
File changes on PR
[#156135566](https://www.pivotaltracker.com/story/show/156135566)
=> chore: Update the front-end

.gitignore, __tests__/ErrorAction.test.jsx, __tests__/incidentAction.test.jsx, mock_endpoints/mockControllers.js, mock_endpoints/mockMiddleware.js, server.js, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx, src/actions/errorAction.jsx, src/actions/timelineAction.jsx
Minor fixes to the timeline sidebar component
Selecting a CC'd person who is an assignee removes them from the assignee section. But selecting an assignee who is in the CC'd section does not remove them from CC'd section.
File changes on PR
=> Chore: Minor fixes

src/pages/Search/Search.Component.jsx
Fix search functionality for staging app
Search functionality in the staging app was not working due to recent changes in API,  it worked only with the mock API. This task fixes the search functionality to work with the API.
File changes in the PR
Change `NODE_ENV` to `production` so the API is used instead of mockAPI and search for a incident using the search bar.
[#156379151](https://www.pivotaltracker.com/story/show/156379151)
=> bug-fix search functionality

__tests__/Dashboard.test.jsx, mock_endpoints/mockData.js, package.json, src/pages/Dashboard/Dashboard.Component.jsx, yarn.lock
- Raises coverage to 92% from 0%.
- We need to raise dashboard test coverage from 0%.
- Go through file changes in PR.
Run yarn test
N/A
[#156127564](https://www.pivotaltracker.com/story/show/156127564)
N/A
=> #156127564 - Tests for Dashboard

__tests__/ButtonComponent.test.jsx, __tests__/CustomMenu.test.jsx
Increases Test Coverage
Adds tests for Button and CustomMenu Component to increase coverage to 100%
File Changes in the PR
Run `yarn test` and look at coverage 
[#156127581](https://www.pivotaltracker.com/story/show/156127581)
=> Increase Test coverage for Button and Custom Menu Components

src/Components/TimelineSidebar/TimelineSidebar.Component.jsx
Removes activity feed feature on incident timeline 
Activity feed was no longer required 
File changes in PR
Run application and navigate to incident timeline to see the activity feed has been removed 
[156757898](https://www.pivotaltracker.com/story/show/156757898)
=> #156757898 Remove Activity feed 

__tests__/IncidentSection.test.jsx, src/Common/NavBar/NavBar.Component.jsx, src/Components/CustomMenu/CustomMenu.Component.jsx, src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentSection.Component.jsx, src/actions/actionTypes.jsx, src/actions/incidentAction.jsx, src/actions/timelineAction.jsx, src/actions/tokenAction.jsx, src/pages/Dashboard/Dashboard.Component.jsx, src/pages/IncidentTimeline/IncidentTimeline.Component.jsx, src/pages/Login/LoginPage.Component.jsx, src/pages/Search/Search.Component.jsx, src/reducers/errorReducer.jsx, src/reducers/initialState.jsx, src/reducers/loadingReducer.jsx, src/reducers/rootReducer.jsx, src/reducers/tokenReducer.jsx
Fix bug that causes the login page to be displayed for a split second after one logs in, before
redirecting to /dashboard.
View file changes in PR.
Attempt to reproduce the bug above when logging in.
=> chore: Fix login bug

__tests__/IncidentSection.test.jsx, src/Common/NavBar/NavBar.Component.jsx, src/Components/CustomMenu/CustomMenu.Component.jsx, src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentSection.Component.jsx, src/actions/actionTypes.jsx, src/actions/incidentAction.jsx, src/actions/timelineAction.jsx, src/actions/tokenAction.jsx, src/pages/Dashboard/Dashboard.Component.jsx, src/pages/IncidentTimeline/IncidentTimeline.Component.jsx, src/pages/Login/LoginPage.Component.jsx, src/pages/Search/Search.Component.jsx, src/reducers/errorReducer.jsx, src/reducers/initialState.jsx, src/reducers/loadingReducer.jsx, src/reducers/rootReducer.jsx, src/reducers/tokenReducer.jsx
- Fix bug that causes the login page to be displayed for a split second after one logs in, before
redirecting to /dashboard
=> fix: Login Bug

Dockerfile
updates serve command in dockerfile to supported version
running the built docker image
[#158432950](https://www.pivotaltracker.com/story/show/158432950)
=> change server version to supported in dockerfile

.env, .gitignore, src/config/index.jsx
Makes changes by passing env variables directly.
Debug wire-frontend login bug
=> Ci pipeline 157974590

src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentFilter/IncidentFilter.scss, src/pages/Dashboard/Dashboard.Component.jsx
Adds an 'All' Button to date filter.
N/A
File changes in PR
Go to the app dashboard and click on the date filters 
An 'All' button was missing from the date filter 
[#158489314](https://www.pivotaltracker.com/story/show/158489314)
N/A
=> Add Button to get all incidents in duration filter

__tests__/Dashboard.test.jsx, __tests__/IncidentCard.test.jsx, __tests__/IncidentList.test.jsx, mock_endpoints/mockData.js, src/Common/NavBar/NavBar.scss, src/Components/CustomMenu/CustomMenu.Component.jsx, src/Components/IncidentFilter/IncidentFilter.Component.jsx, src/Components/IncidentFilter/IncidentFilter.scss, src/Components/IncidentList/IncidentCard.Component.jsx, src/Components/IncidentList/IncidentList.Component.jsx, src/Components/IncidentList/IncidentList.scss, src/Components/IncidentType/IncidentType.Component.jsx, src/Components/IncidentType/IncidentType.scss, src/pages/Dashboard/Dashboard.Component.jsx, src/pages/Search/Search.scss
- Changes the default filter on Dashboard from `All Incidents` to `Pending`.
- **See screenshots section**
- One can change the filter to other incident categories, for instance `In Progress`
- The styling has been coded to resemble Humphrey's designs as closely as possible.
- View file changes on PR
- Fire the app up on localhost, and navigate to login. You'll redirect to /dashboard.
=> feat: Change default filter on Dashboard from 'All Incidents' to 'Pending'

src/Common/NavBar/NavBar.scss, src/Components/IncidentFilter/IncidentFilter.scss
Fixes a bug with the drop down menu for logging out 
The drop down menu kept disappearing making logging out difficult, this PR fixes that issue 
[#158722507](https://www.pivotaltracker.com/story/show/158722507)
=> Fix Profile dropdown menu stays open on hover 

mock_endpoints/mockControllers.js, mock_endpoints/mockData.js, src/Common/NavBar/NavBar.Component.jsx, src/Components/App.jsx, src/Components/AvailableUser/AvailableUser.Component.jsx, src/Components/TimelineSidebar/TimelineSidebar.Component.jsx
- Once users are selected as 'ccd' on the incident timeline, they no longer disappear on refresh
- Also, hide the notification icon on NavBar till we have the functionality for it.
N/A
- View file changes on PR
- Visit an incident's timeline page, and assign a user the incident, and cc a couple more. Your selections will `not` disappear on refresh 
N/A
[#160379408](https://www.pivotaltracker.com/story/show/160379408)
N/A
=> fix: Selecting users as 'ccd' or 'assigned'

mock_endpoints/mockData.js, src/Components/AvailableUser/AvailableUser.Component.jsx, src/Components/AvailableUser/AvailableUser.scss, src/Components/Modal/Modal.Component.jsx, src/Components/Modal/Modal.scss, src/Components/UserFilter/UserFilter.Component.jsx, src/Components/UserFilter/UserFilter.scss, src/pages/AdminDashboard/AdminDashboard.scss
- Fix admin dashboard UI to resemble the current mockup
- Make the dashboard cleaner and visually appealing 
View file changes on PR.
-  Log in to wire on localhost as an admin, access the dashboard from the drop-down settings on your profile
N/A
=> Fix admin dashboard UI/UX
